name: "Shairport Sync MQTT"
description: "Shairport Sync with MQTT for AirPlay (full audio + JSON support)"
version: "1.1.1"
slug: "shairport_sync_mqtt"
init: false
arch:
  - aarch64
startup: application
boot: auto
host_network: true
audio: true
udev: true

map:
  - config:rw
  - share:rw

options:
  log_level: "debug"
  device: "default"
  mqtt_enabled: true
  mqtt_host: "192.168.0.123"
  mqtt_port: 1883
  mqtt_username: "tripl"
  mqtt_password: "Fylhtq3120"
  mqtt_topic_prefix: "Shairport"

schema:
  log_level: "list(debug|info|warn|error)"
  device: "str"
  mqtt_enabled: "bool"
  mqtt_host: "str"
  mqtt_port: "int"
  mqtt_username: "str"
  mqtt_password: "password"
  mqtt_topic_prefix: "str"
