name: "Shairport Sync MQTT"
description: "Shairport Sync with MQTT for AirPlay"
version: "1.0.11"
slug: "shairport_sync_mqtt"
init: false
arch:
  - armv7
  - aarch64
  - amd64
build: .
startup: application
boot: auto
host_network: true
devices:
  - /dev/snd:/dev/snd:rwm
map:
  - config:rw
options:
  log_level: "debug"
  audio_device: "hw:2,0"
  mqtt_enabled: true
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: "tripl"
  mqtt_password: "Fylhtq3120"
  mqtt_topic_prefix: "shairport"
schema:
  log_level: "list(debug|info|warn|error)"
  audio_device: "str"
  mqtt_enabled: "bool"
  mqtt_host: "str"
  mqtt_port: "int"
  mqtt_username: "str"
  mqtt_password: "password"
  mqtt_topic_prefix: "str"
